<a href="https://colab.research.google.com/github/AnvarjonIbrohimov/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.2

In [33]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford","Testa", "KIA", "Hyundai"],
    'counts': [3,2,5,4,7,2]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       2
2     Ford       5
3    Testa       4
4      KIA       7
5  Hyundai       2

In [12]:
df.head(10) # default 5rows  head() df dagi datalarni korsatish uchun

      cars  conuts
0      BMW       3
1    Volvo       2
2     Ford       5
3    Testa       4
4      KIA       7
5  Hyundai       2

In [16]:
df.tail(2) # ohiridan qiymat bolmasa default 5ta data qaytaradi

      cars  conuts
4      KIA       7
5  Hyundai       2

In [18]:
df.shape  # shapeni aniqlab beradi 6 qator 2ustun

(6, 2)

In [20]:
df.columns  # typeni va column row nomlarini chiqarib beradi

Index(['cars', 'conuts'], dtype='object')

In [21]:
df.dtypes # bu data typelarni qaytaradi ichidagi data typelarni

cars      object
conuts     int64
dtype: object

In [24]:
print(df)

      cars  conuts
0      BMW       3
1    Volvo       2
2     Ford       5
3    Testa       4
4      KIA       7
5  Hyundai       2

In [23]:
df.describe() # nuberical columns only statistika korsatib beradi qator min data max dara std -> standart devietion

         conuts
count  6.000000
mean   3.833333
std    1.940790
min    2.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    7.000000

In [25]:
df.iloc[0] # [1:5] [2:] ichidagi osha indexdagi datani chiqarib beradi

cars      BMW
conuts      3
Name: 0, dtype: object

In [31]:
df.loc[:, "cars"]  #  bu ikta value qabul qiladi 1- data 2-qator nomi

0        BMW
1      Volvo
2       Ford
3      Testa
4        KIA
5    Hyundai
Name: cars, dtype: object

In [37]:
df[df["counts"] != 3  ] # [df["counts"] > 3 bunday qilsa boolean datatype qaytadi  != >= <= hammasi mumkin,  df[df["counts"] == "Testa"  ]

      cars  counts
1    Volvo       2
2     Ford       5
3    Testa       4
4      KIA       7
5  Hyundai       2

In [38]:
df.mean(numeric_only=True) # counts dagi sonlarning ortachasini chiqaradi

counts    3.833333
dtype: float64

In [39]:
df.sum()  # raqamlar yigindisini chiqarib beradi

cars      BMWVolvoFordTestaKIAHyundai
counts                             23
dtype: object

In [40]:
df.min() # eng kichigini chiqarib beradi

cars      BMW
counts      2
dtype: object

In [41]:
df.median(numeric_only=True)

counts    3.5
dtype: float64

In [42]:
df.count() # countlarni chiqarib beradi

cars      6
counts    6
dtype: int64

In [43]:
df.std(numeric_only=True)  # standard

counts    1.94079
dtype: float64

In [44]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Ford", "Chevrolet", "Genisis"],
    "counts": [2,3,None,5,2,4]
}
df2 = pd.DataFrame(data_with_missing)
print(df2)

        cars  counts
0        BMW     2.0
1      Volvo     3.0
2       None     NaN
3       Ford     5.0
4  Chevrolet     2.0
5    Genisis     4.0

In [46]:
df2.isnull().sum() # null qiymat bormi bolsa sum() yani nechta?

cars      1
counts    1
dtype: int64

In [47]:
df2.dropna() # null qiymatdagi qatorlarni ochirib tashlaydi

        cars  counts
0        BMW     2.0
1      Volvo     3.0
3       Ford     5.0
4  Chevrolet     2.0
5    Genisis     4.0

In [49]:
print(df2)

        cars  counts
0        BMW     2.0
1      Volvo     3.0
2       None     NaN
3       Ford     5.0
4  Chevrolet     2.0
5    Genisis     4.0

In [51]:
df2.fillna("empty") # null qiymatlar orniga shu qiymatni qoyib beradi!

        cars counts
0        BMW    2.0
1      Volvo    3.0
2      empty  empty
3       Ford    5.0
4  Chevrolet    2.0
5    Genisis    4.0

In [54]:
df2.fillna({"cars": "empty", "counts": 0}) # null qiymatlar orniga shu qiymatni qoyib beradi!

        cars  counts
0        BMW     2.0
1      Volvo     3.0
2      empty     0.0
3       Ford     5.0
4  Chevrolet     2.0
5    Genisis     4.0

In [63]:
# df = pd.read_csv("Titanic-Dataset.csv")
# df.head(30)
df = pd.read_excel("test.xlsx")
df.tail()

# df = pd.read_json("file_name.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [64]:
df.to_excel("test.xlsx")

In [67]:
# Series  = 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [69]:
cars_series = df2['cars']
print('cars_series: ', cars_series)

cars_series:  0          BMW
1        Volvo
2         None
3         Ford
4    Chevrolet
5      Genisis
Name: cars, dtype: object